const vocabList = require("../data/vocabList.json")

export default function getListOfLanguageWords() {
    return vocabList;
    /*return [
        {"en": "0", "new": "zero"},
        {"en": "1", "new": "uno"},
        {"en": "2", "new": "due"},
        {"en": "3", "new": "tre"},
        {"en": "4", "new": "quattro"},
        {"en": "5", "new": "cinque"},
        {"en": "6", "new": "sei"},
        {"en": "7", "new": "sette"},
        {"en": "8", "new": "otto"},
        {"en": "9", "new": "nove"},
        {"en": "10", "new": "dieci"},
        {"en": "11", "new": "undici"},
        {"en": "0", "new": "zero"},
        {"en": "1", "new": "uno"},
        {"en": "2", "new": "due"},
        {"en": "3", "new": "tre"},
        {"en": "4", "new": "quattro"},
        {"en": "5", "new": "cinque"},
        {"en": "6", "new": "sei"},
        {"en": "7", "new": "sette"},
        {"en": "8", "new": "otto"},
        {"en": "9", "new": "nove"},
        {"en": "10", "new": "dieci"},
        {"en": "11", "new": "undici"},
        {"en": "0", "new": "zero"},
        {"en": "1", "new": "uno"},
        {"en": "2", "new": "due"},
        {"en": "3", "new": "tre"},
        {"en": "4", "new": "quattro"},
        {"en": "5", "new": "cinque"},
        {"en": "6", "new": "sei"},
        {"en": "7", "new": "sette"},
        {"en": "8", "new": "otto"},
        {"en": "9", "new": "nove"},
        {"en": "10", "new": "dieci"},
        {"en": "11", "new": "undici"},
        {"en": "0", "new": "zero"},
        {"en": "1", "new": "uno"},
        {"en": "2", "new": "due"},
        {"en": "3", "new": "tre"},
        {"en": "4", "new": "quattro"},
        {"en": "5", "new": "cinque"},
        {"en": "6", "new": "sei"},
        {"en": "7", "new": "sette"},
        {"en": "8", "new": "otto"},
        {"en": "9", "new": "nove"},
        {"en": "10", "new": "dieci"},
        {"en": "11", "new": "undici"},
        {"en": "0", "new": "zero"},
        {"en": "1", "new": "uno"},
        {"en": "2", "new": "due"},
        {"en": "3", "new": "tre"},
        {"en": "4", "new": "quattro"},
        {"en": "5", "new": "cinque"},
        {"en": "6", "new": "sei"},
        {"en": "7", "new": "sette"},
        {"en": "8", "new": "otto"},
        {"en": "9", "new": "nove"},
        {"en": "10", "new": "dieci"},
        {"en": "11", "new": "undici"},
    ];*/
}